const freinds = [
  { id: 1, name: "Kundan", profile: "https://randomuse" },
  { id: 2, name: "Jane Doe", profile: "https://randomuse" },
  { id: 3, name: "John Smith", profile: "" },
  { id: 4, name: "Jane Smith", profile: "https://randomuse" },
  { id: 5, name: "John Doe", profile: "https://randomuse" },
  { id: 6, name: "Jane Doe", profile: "https://randomuse" },
  { id: 7, name: "John Smith", profile: "" },
  { id: 8, name: "Jane Smith", profile: "https://randomuse" },
  { id: 9, name: "John Doe", profile: "https://randomuse" },
  { id: 10, name: "Jane Doe", profile: "https://randomuse" },
  { id: 11, name: "John Smith", profile: "" },
  { id: 12, name: "Jane Smith", profile: "https://randomuse" },
  { id: 13, name: "John Doe", profile: "https://randomuse" },
  { id: 14, name: "Jane Doe", profile: "https://randomuse" },
  { id: 15, name: "John Smith", profile: "" },
  { id: 16, name: "Jane Smith", profile: "https://randomuse" },
  { id: 17, name: "John Doe", profile: "https://randomuse" },
  { id: 18, name: "Jane Doe", profile: "https://randomuse" },
  { id: 19, name: "John Smith", profile: "" },
  { id: 20, name: "Jane Smith", profile: "https://randomuse" },
  { id: 21, name: "John Doe", profile: "https://randomuse" },
  { id: 22, name: "Jane Doe", profile: "https://randomuse" },
  { id: 23, name: "John Smith", profile: "" },
  { id: 24, name: "Jane Smith", profile: "https://randomuse" },
  { id: 25, name: "John Doe", profile: "https://randomuse" },
  { id: 26, name: "Jane Doe", profile: "https://randomuse" },
  { id: 27, name: "John Smith", profile: "" },
  { id: 28, name: "Jane Smith", profile: "https://randomuse" },
  { id: 29, name: "John Doe", profile: "https://randomuse" },
  { id: 30, name: "Jane Doe", profile: "https://randomuse" },
  { id: 31, name: "John Smith", profile: "" },
  { id: 32, name: "Jane Smith", profile: "https://randomuse" },
  { id: 33, name: "John Doe", profile: "https://randomuse" },
  { id: 34, name: "Jane Doe", profile: "https://randomuse" },
  { id: 35, name: "John Smith", profile: "" },
  { id: 36, name: "AYush", profile: "https://randomuse" },
];
export { freinds };
